[options]
addons_path = addons,odoo-enterprise
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
pg_path = /opt/homebrew/opt/postgresql@14/bin
limit_memory_hard = 0
limit_memory_soft = 0
admin_passwd = $pbkdf2-sha512$600000$QChlDAEgROidcy7FGENobQ$iPIMhA1h..130bQ9tZx/K3R4RrAsipUTMTpD03sDnNFWx5p0LtHislVeaCIuezpfG/I2UrH2YyBeE1oVt/6Djw
#admin123
